name: recipoints
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  get: ^4.6.6
  go_router: ^14.2.7
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
 